//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HFDIncidents.IncidentLoader.HoustonFireDept {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HoustonFireDept.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponse HelloWorld(HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponse> HelloWorldAsync(HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name HelloPersonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloPerson", ReplyAction="*")]
        HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponse HelloPerson(HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloPerson", ReplyAction="*")]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponse> HelloPersonAsync(HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest request);
        
        // CODEGEN: Generating message contract since element name GetIncidentsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncidents", ReplyAction="*")]
        HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponse GetIncidents(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncidents", ReplyAction="*")]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponse> GetIncidentsAsync(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest request);
        
        // CODEGEN: Generating message contract since element name GetIncidentsPOSTResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncidentsPOST", ReplyAction="*")]
        HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponse GetIncidentsPOST(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncidentsPOST", ReplyAction="*")]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponse> GetIncidentsPOSTAsync(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloPersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloPerson", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequestBody Body;
        
        public HelloPersonRequest() {
        }
        
        public HelloPersonRequest(HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloPersonRequestBody {
        
        public HelloPersonRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloPersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloPersonResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponseBody Body;
        
        public HelloPersonResponse() {
        }
        
        public HelloPersonResponse(HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloPersonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object HelloPersonResult;
        
        public HelloPersonResponseBody() {
        }
        
        public HelloPersonResponseBody(object HelloPersonResult) {
            this.HelloPersonResult = HelloPersonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIncidentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIncidents", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequestBody Body;
        
        public GetIncidentsRequest() {
        }
        
        public GetIncidentsRequest(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIncidentsRequestBody {
        
        public GetIncidentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIncidentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIncidentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponseBody Body;
        
        public GetIncidentsResponse() {
        }
        
        public GetIncidentsResponse(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIncidentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIncidentsResult;
        
        public GetIncidentsResponseBody() {
        }
        
        public GetIncidentsResponseBody(string GetIncidentsResult) {
            this.GetIncidentsResult = GetIncidentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIncidentsPOSTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIncidentsPOST", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequestBody Body;
        
        public GetIncidentsPOSTRequest() {
        }
        
        public GetIncidentsPOSTRequest(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetIncidentsPOSTRequestBody {
        
        public GetIncidentsPOSTRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIncidentsPOSTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIncidentsPOSTResponse", Namespace="http://tempuri.org/", Order=0)]
        public HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponseBody Body;
        
        public GetIncidentsPOSTResponse() {
        }
        
        public GetIncidentsPOSTResponse(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIncidentsPOSTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIncidentsPOSTResult;
        
        public GetIncidentsPOSTResponseBody() {
        }
        
        public GetIncidentsPOSTResponseBody(string GetIncidentsPOSTResult) {
            this.GetIncidentsPOSTResult = GetIncidentsPOSTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap>, HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponse HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.HelloWorld(HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequestBody();
            HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponse retVal = ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponse> HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.HelloWorldAsync(HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldResponse> HelloWorldAsync() {
            HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloWorldRequestBody();
            return ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponse HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.HelloPerson(HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest request) {
            return base.Channel.HelloPerson(request);
        }
        
        public object HelloPerson() {
            HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequestBody();
            HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponse retVal = ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).HelloPerson(inValue);
            return retVal.Body.HelloPersonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponse> HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.HelloPersonAsync(HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest request) {
            return base.Channel.HelloPersonAsync(request);
        }
        
        public System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonResponse> HelloPersonAsync() {
            HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.HelloPersonRequestBody();
            return ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).HelloPersonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponse HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.GetIncidents(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest request) {
            return base.Channel.GetIncidents(request);
        }
        
        public string GetIncidents() {
            HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequestBody();
            HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponse retVal = ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).GetIncidents(inValue);
            return retVal.Body.GetIncidentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponse> HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.GetIncidentsAsync(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest request) {
            return base.Channel.GetIncidentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsResponse> GetIncidentsAsync() {
            HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsRequestBody();
            return ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).GetIncidentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponse HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.GetIncidentsPOST(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest request) {
            return base.Channel.GetIncidentsPOST(request);
        }
        
        public string GetIncidentsPOST() {
            HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequestBody();
            HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponse retVal = ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).GetIncidentsPOST(inValue);
            return retVal.Body.GetIncidentsPOSTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponse> HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap.GetIncidentsPOSTAsync(HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest request) {
            return base.Channel.GetIncidentsPOSTAsync(request);
        }
        
        public System.Threading.Tasks.Task<HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTResponse> GetIncidentsPOSTAsync() {
            HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest inValue = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequest();
            inValue.Body = new HFDIncidents.IncidentLoader.HoustonFireDept.GetIncidentsPOSTRequestBody();
            return ((HFDIncidents.IncidentLoader.HoustonFireDept.WebService1Soap)(this)).GetIncidentsPOSTAsync(inValue);
        }
    }
}
